export const blogPosts = [
	{
		slug: "que-se-puede-enviar-a-cuba-2026",
		title: "Qué se puede enviar a Cuba en 2026",
		description:
			"Resumen práctico de artículos permitidos para envíos a Cuba desde Miami y cómo preparar tu paquete.",
		primaryKeyword: "que se puede enviar a cuba",
		publishedAt: "2026-02-26",
		readTime: "6 min",
		image: "/banner-envios-cuba-compressed.jpg",
		imageAlt: "Paquete listo para envío a Cuba desde Miami",
		content: [
			"Antes de armar tu caja, define qué tipo de envío necesitas: marítimo para volumen y ahorro, o aéreo para urgencias. Esta decisión evita pagar de más por artículos que no requieren rapidez.",
			"En la práctica, lo más enviado desde Miami a Cuba es ropa, calzado, artículos de aseo, alimentos no perecederos y pequeños electrodomésticos permitidos. Lo ideal es agrupar por categorías para declarar mejor.",
			"Cada artículo debe ir identificado de forma específica. En vez de poner solo 'misceláneas', conviene declarar 'ropa de niño', 'jabón de tocador', 'latas de atún' o 'cafetera doméstica'.",
			"Cuando el paquete mezcla alimentos y equipos, separa por bolsas internas o cajas pequeñas. Eso reduce incidencias en revisiones y facilita el control del contenido por parte de aduana.",
			"Guarda fotos del paquete antes de cerrarlo y del contenido principal. Este registro te ayuda si luego necesitas aclarar una reclamación o validar lo que fue entregado.",
			"Las reglas aduanales pueden cambiar durante el año. Antes de enviar, confirma con tu agencia la lista vigente de artículos permitidos para evitar retenciones o recargos innecesarios.",
		],
	},
	{
		slug: "articulos-prohibidos-cuba",
		title: "Lista de artículos prohibidos en Cuba",
		description:
			"Conoce qué no se puede enviar a Cuba para evitar retenciones, multas o devoluciones de tu paquete.",
		primaryKeyword: "que no se puede enviar a cuba",
		publishedAt: "2026-02-26",
		readTime: "5 min",
		image: "/ship-new.jpg",
		imageAlt: "Caja de envío con etiqueta de precaución",
		content: [
			"Uno de los errores más costosos es incluir artículos restringidos en un paquete aparentemente normal. Un solo producto no permitido puede provocar retención total o demoras largas.",
			"Evita enviar armas, municiones, explosivos, sustancias ilegales, dinero en efectivo y productos de alto riesgo. También debes evitar cualquier artículo que viole regulaciones de transporte internacional.",
			"En algunos casos, artículos aparentemente comunes requieren condiciones especiales de envío o documentación adicional. Por eso no conviene asumir: siempre valida antes de cerrar la caja.",
			"La declaración incompleta también genera problemas. Si escribes descripciones genéricas, aumenta la probabilidad de revisión adicional y de diferencias entre lo declarado y lo inspeccionado.",
			"Si tienes dudas sobre un artículo específico, envía foto y descripción por WhatsApp a tu agencia antes de pagar. Resolver esa duda en origen te ahorra tiempo y dinero en destino.",
			"Revisa la lista actualizada de restricciones cada vez que hagas un envío. No uses como referencia una guía antigua, porque los criterios pueden cambiar según normativa vigente.",
		],
	},
	{
		slug: "cuanto-demora-envio-maritimo-cuba",
		title: "Cuánto demora un envío marítimo a Cuba",
		description:
			"Tiempos promedio del envío marítimo a Cuba y factores que afectan la entrega final puerta a puerta.",
		primaryKeyword: "cuanto demora envio maritimo cuba",
		publishedAt: "2026-02-26",
		readTime: "4 min",
		image: "/ship.jpg",
		imageAlt: "Buque de carga para envíos marítimos a Cuba",
		content: [
			"El envío marítimo a Cuba suele tardar entre 30 y 45 días laborables en condiciones normales. Este rango puede variar según la ciudad de destino y la carga operativa de temporada.",
			"Los principales factores que impactan el tiempo son: salida del contenedor, validación aduanal, clasificación local y ruta final de reparto puerta a puerta.",
			"Las provincias orientales pueden tardar más que zonas de mayor concentración logística. Por eso es útil pedir estimado por provincia, no solo un tiempo promedio general.",
			"En fechas de alta demanda, como campañas familiares o periodos festivos, los tiempos pueden extenderse. Planificar con antelación reduce estrés y costos por urgencia.",
			"Una declaración clara y un empaque correcto ayudan a disminuir revisiones adicionales. Si el contenido es ambiguo, el proceso de liberación puede tardar más de lo previsto.",
			"Para tener control del proceso, usa el número de tracking y consulta eventos clave del envío. Si observas estancamiento operativo, contacta soporte con datos completos del destinatario.",
		],
	},
	{
		slug: "cuanto-cuesta-enviar-a-cuba-desde-miami",
		title: "Cuánto cuesta enviar a Cuba desde Miami",
		description:
			"Factores que determinan el precio por libra en envíos a Cuba y cómo conseguir una cotización precisa.",
		primaryKeyword: "cuanto cuesta enviar a cuba",
		publishedAt: "2026-02-26",
		readTime: "5 min",
		image: "/banner-discounts-compressed.jpg",
		imageAlt: "Promoción de precios por libra para envíos a Cuba",
		content: [
			"El precio final de un envío a Cuba no depende solo de la libra. También influyen el volumen, el tipo de artículo, el método de transporte y posibles requisitos aduanales.",
			"En marítimo, normalmente obtienes mejor costo por libra para paquetes grandes. En aéreo, pagas más por rapidez, lo cual puede ser útil para medicinas o envíos urgentes.",
			"Las promociones semanales o por temporada pueden cambiar bastante el costo total. Vale la pena cotizar en el momento exacto en que vas a enviar, no con tarifas antiguas.",
			"Para una cotización precisa, comparte peso aproximado, medidas de la caja y lista de contenido. Mientras más exacta sea tu información, menor diferencia habrá al facturar.",
			"Si envías electrodomésticos o paquetes mixtos, pide evaluación específica. Estos casos suelen tener particularidades de manejo y declaración que impactan el valor final.",
			"Una buena cotización no solo te da precio: también debe incluir tiempo estimado, condiciones y recomendaciones para evitar retrasos o costos adicionales.",
		],
	},
	{
		slug: "limites-alimentos-aduana-cuba",
		title: "Límites de alimentos en aduana Cuba",
		description:
			"Guía práctica para enviar alimentos a Cuba cumpliendo límites y buenas prácticas de empaque.",
		primaryKeyword: "aduana cuba alimentos limite",
		publishedAt: "2026-03-05",
		readTime: "6 min",
		image: "/cuba-boxes.png",
		imageAlt: "Cajas de alimentos preparadas para envío a Cuba",
		content: [
			"Para enviar alimentos a Cuba sin complicaciones, prioriza productos no perecederos, sellados de fábrica y con etiquetado legible.",
			"Evita envases dañados o sin identificación, porque eso puede activar revisión adicional o rechazo parcial del contenido en el proceso de inspección.",
			"Una práctica útil es organizar los alimentos por tipo: granos, enlatados, aseo alimentario y suplementos. Esa clasificación facilita la declaración y el control del paquete.",
			"Si mezclas alimentos con otros artículos, separa por capas o cajas internas para reducir contaminación, daño y confusiones durante manipulación logística.",
			"Antes de enviar, consulta límites actualizados y condiciones vigentes. Los criterios aduanales pueden variar y es mejor validar cada envío en tiempo real.",
			"Un empaque limpio, ordenado y bien declarado reduce incidencias y mejora la probabilidad de entrega sin demoras innecesarias.",
		],
	},
	{
		slug: "como-enviar-medicinas-a-cuba",
		title: "Cómo enviar medicinas a Cuba legalmente",
		description:
			"Pasos recomendados para enviar medicinas a Cuba de forma segura y con menor riesgo de incidencias.",
		primaryKeyword: "limite medicinas cuba",
		publishedAt: "2026-03-12",
		readTime: "6 min",
		image: "/truck-compressed.jpg",
		imageAlt: "Transporte logístico para envíos urgentes a Cuba",
		content: [
			"Si necesitas enviar medicinas a Cuba, la prioridad es cumplir con identificación, empaque y declaración clara del contenido.",
			"Siempre que sea posible, conserva la medicina en su empaque original y evita fraccionar productos sin etiqueta. Esto ayuda durante inspección y verificación.",
			"Clasifica por tipo de medicamento y separa en bolsas internas. Una caja ordenada reduce errores y facilita revisiones aduanales.",
			"Cuando aplique, incluye documentación de respaldo o indicaciones médicas básicas. Esto puede ser clave para justificar la naturaleza del envío.",
			"No todos los productos farmacéuticos tienen el mismo tratamiento logístico. Antes de enviar, valida límites y condiciones vigentes con tu agencia.",
			"Si el envío es urgente, compara marítimo y aéreo según tiempo objetivo. Elegir bien el método evita costos dobles por reprocesos.",
		],
	},
	{
		slug: "envio-maritimo-vs-aereo-cuba",
		title: "Diferencia entre envío marítimo vs aéreo a Cuba",
		description:
			"Comparativa clara para elegir entre envío marítimo o aéreo según urgencia, costo y tipo de paquete.",
		primaryKeyword: "diferencia envio maritimo vs aereo cuba",
		publishedAt: "2026-03-19",
		readTime: "5 min",
		image: "/ship2.jpg",
		imageAlt: "Comparación entre transporte marítimo y aéreo",
		content: [
			"Elegir entre marítimo y aéreo depende de tres variables: urgencia, presupuesto y tipo de carga.",
			"El marítimo es ideal para paquetes pesados o de mayor volumen porque suele ofrecer mejor precio por libra.",
			"El aéreo es la opción adecuada cuando el tiempo es crítico: medicinas, documentos o artículos prioritarios.",
			"Si buscas ahorrar, marítimo suele ser más conveniente. Si buscas velocidad, el aéreo compensa por su menor tiempo de tránsito.",
			"También influye la sensibilidad del contenido. Para artículos delicados, conviene evaluar método, empaque y protección adicional.",
			"La mejor decisión no es universal: pide una cotización comparativa con tiempo estimado para ambos métodos y elige según objetivo real.",
		],
	},
	{
		slug: "consejos-empacar-paquetes-cuba",
		title: "Consejos para empacar paquetes a Cuba",
		description:
			"Recomendaciones simples para proteger tu paquete y evitar daños durante el envío a Cuba.",
		primaryKeyword: "consejos para empacar paquetes a cuba",
		publishedAt: "2026-03-26",
		readTime: "4 min",
		image: "/envios_cuba_madres-compressed.jpg",
		imageAlt: "Empaque correcto de cajas para envíos a Cuba",
		content: [
			"Un buen empaque reduce daños, retrasos y reclamos. Empieza con una caja resistente al peso y al transporte prolongado.",
			"Refuerza todas las uniones con cinta de buena calidad y evita dejar espacios internos vacíos que permitan movimiento brusco.",
			"Si envías artículos frágiles, usa protección por capas: burbuja, cartón interno y relleno de amortiguación.",
			"Distribuye el peso de forma uniforme. Una carga desequilibrada aumenta el riesgo de golpes y deformación de la caja.",
			"Etiqueta correctamente el paquete con datos legibles del destinatario y remitente, incluyendo contacto actualizado.",
			"Antes de entregar, toma fotos del contenido y del paquete cerrado. Ese respaldo es útil si luego necesitas aclarar una incidencia.",
		],
	},
	{
		slug: "mejores-agencias-envios-cuba-miami",
		title: "Mejores agencias de envíos a Cuba en Miami",
		description:
			"Criterios para elegir una agencia de envíos a Cuba confiable en Miami y evitar malas experiencias.",
		primaryKeyword: "mejores agencias envios cuba",
		publishedAt: "2026-04-02",
		readTime: "5 min",
		image: "/ctelogo.png",
		imageAlt: "Logo de CTEnvios en agencia de Miami",
		content: [
			"Elegir agencia no es solo comparar precio por libra. También debes evaluar cumplimiento, soporte y claridad en condiciones de servicio.",
			"Una agencia confiable explica tiempos estimados por tipo de envío, posibles variaciones y proceso de seguimiento.",
			"Revisa reseñas reales y recientes, especialmente comentarios sobre atención ante incidencias y cumplimiento de entrega.",
			"Pregunta si ofrecen tracking, asesoría aduanal y canal directo de soporte por WhatsApp. Estos puntos marcan diferencia en la experiencia final.",
			"Evita decidir solo por promociones agresivas. Una tarifa baja sin respaldo operativo puede salir más cara por retrasos o problemas de gestión.",
			"Busca consistencia: comunicación clara, proceso ordenado y respuestas rápidas antes y después de enviar.",
		],
	},
	{
		slug: "como-rastrear-un-envio-a-cuba",
		title: "Cómo rastrear un envío a Cuba",
		description:
			"Aprende a usar tu número de tracking para consultar estado, incidencias y estimado de entrega.",
		primaryKeyword: "como rastrear un envio a cuba",
		publishedAt: "2026-04-09",
		readTime: "4 min",
		image: "/truck.webp",
		imageAlt: "Camión de reparto para seguimiento de envíos",
		content: [
			"El tracking te permite conocer el estado real de tu envío y anticiparte a posibles incidencias.",
			"Con el número de guía puedes revisar eventos del paquete: recibido, en tránsito, en proceso local o entregado.",
			"Si el estado no cambia por varios días, valida primero el tiempo estimado de esa etapa antes de asumir un problema.",
			"Cuando necesites soporte, comparte número de tracking, nombre del destinatario y teléfono de contacto para acelerar la gestión.",
			"Un seguimiento activo ayuda a reaccionar rápido en casos de datos incompletos, ajustes de ruta o validaciones adicionales.",
			"Revisar periódicamente el tracking reduce incertidumbre y mejora la coordinación con tu familiar en destino.",
		],
	},
	{
		slug: "impuestos-aduana-cuba-2026",
		title: "Impuestos de aduana Cuba 2026: guía básica",
		description:
			"Puntos clave sobre impuestos aduanales en Cuba y cómo preparar tu envío para evitar sorpresas.",
		primaryKeyword: "impuestos aduana cuba",
		publishedAt: "2026-04-16",
		readTime: "6 min",
		image: "/cuba-habana-skyline.png",
		imageAlt: "Ciudad de La Habana y contexto aduanal de Cuba",
		content: [
			"Los impuestos aduanales en Cuba dependen del tipo de artículo, valor declarado y normativa vigente al momento del arribo.",
			"Por eso, la declaración en origen debe ser precisa y coherente con el contenido real del paquete.",
			"Cuando hay diferencias entre declaración y revisión, pueden aparecer recálculos, demoras o procesos adicionales de validación.",
			"En artículos de mayor valor, conviene confirmar criterios de clasificación antes de enviar para evitar sorpresas en destino.",
			"No uses tablas antiguas o estimados informales para calcular impuestos. Lo correcto es validar con información actualizada.",
			"Una buena asesoría previa reduce riesgo financiero y te ayuda a planificar mejor el costo total del envío.",
		],
	},
	{
		slug: "errores-comunes-al-enviar-paquetes-cuba",
		title: "Errores comunes al enviar paquetes a Cuba",
		description:
			"Evita los fallos más frecuentes que elevan costos o retrasan entregas en envíos a Cuba.",
		primaryKeyword: "errores comunes enviar paquetes cuba",
		publishedAt: "2026-04-23",
		readTime: "5 min",
		image: "/ship.webp",
		imageAlt: "Caja de envío preparada para evitar errores comunes",
		content: [
			"Muchos problemas en envíos a Cuba no ocurren en destino, sino en la preparación del paquete en origen.",
			"Error frecuente: cotizar sin peso ni medidas reales. Eso genera diferencias de precio al momento de registrar el envío.",
			"Error frecuente: declarar contenido ambiguo. Las descripciones genéricas aumentan revisiones y retrasos.",
			"Error frecuente: elegir método de transporte sin considerar urgencia. No todo requiere aéreo, ni todo conviene marítimo.",
			"Error frecuente: usar empaque débil para artículos pesados o frágiles. Un mal embalaje multiplica riesgo de daño.",
			"Error frecuente: no guardar evidencia del contenido. Fotos y lista simple de artículos son clave ante cualquier reclamación.",
		],
	},
];

export const blogPostSlugs = blogPosts.map((post) => post.slug);
